name: ChatGPT Code Review

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: |
            .github/scripts/code-review/node_modules
            .github/scripts/code-review/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('.github/scripts/code-review/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install review script deps
        run: cd .github/scripts/code-review && yarn install --frozen-lockfile

      - name: Run ChatGPT review
        run: cd .github/scripts/code-review && yarn review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
